#!/bin/bash

apt-get remove -y zimbra-logger zimbra-dnscache zimbra-snmp zimbra-apache zimbra-spell
/opt/zimbra/libexec/zmsetup.pl -c /zimbra/zimbra-config
/bin/bash /zimbra/update-zimbra
sudo -i -u zimbra /bin/bash -c "vncserver :1 -geometry 1680x1050 -depth 24" && tail -f /var/log/zimbra.log
