#!/bin/bash
# Do this after a ZCS install to fix necessary permissions
# requires sudo/root
# if [ "$USER" != "root" ]; then
#     echo "must run this script as root" 1>&2
#     exit 1
# fi

DN=$(dirname $0)
chown zimbra:zimbra /opt/zimbra/.
chown zimbra:zimbra /opt/zimbra/.*
chmod -R o+w /opt/zimbra/lib/
chmod -R o+w /opt/zimbra/jetty/
chmod -R o+w /opt/zimbra/common/etc/openldap/schema
chmod o+w /opt/zimbra/conf/zimbra.ldif
chmod +w /opt/zimbra/conf/attrs/zimbra-attrs.xml
chmod -R o+w /opt/zimbra/common/etc/openldap/zimbra
cp ${DN}/junit-4.8.2.jar  /opt/zimbra/jetty/webapps/service/WEB-INF/lib/.
echo "zimbra:zimbra" | chpasswd
mkdir /opt/zimbra/.vnc
chown zimbra:zimbra /opt/zimbra/.vnc
echo "zimbra" | vncpasswd -f > /opt/zimbra/.vnc/passwd
chown zimbra:zimbra /opt/zimbra/.vnc/passwd

OZ=${DN}/opt-zimbra
for f in $(ls ${OZ})
do
    F=${OZ}/${f}
    if [ "$f" = "DOT-ssh" ]
    then
        cp ${F}/* /opt/zimbra/.ssh
        chown zimbra /opt/zimbra/.ssh/*
    fi

    if [ -f "${F}" ]
    then
        F2=".$(echo ${f} | tr -d 'DOT-')"
        cp "${F}" "/opt/zimbra/${F2}"
        chown zimbra "/opt/zimbra/${F2}"
    fi
done
